"""
Django settings for Hivemind project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Attention!!
# Update this settings variable when releasing a new version of Hivemind
# such as when there are changes to db models
RELEASE_VERSION = 'v0.6.4'

from os import environ, path

from django.core.urlresolvers import reverse_lazy

from .drf import REST_FRAMEWORK

SRC_DIR = path.dirname(path.dirname(path.dirname(path.abspath(__file__))))
BASE_DIR = path.dirname(SRC_DIR)

from .haystack import HAYSTACK_CONNECTIONS, HAYSTACK_SIGNAL_PROCESSOR

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'crispy_forms',
    'taggit',
    'rest_framework',
    'haystack',
]

HIVEMIND_APPS = [
    'common',
    'comments',
    'defects',
    'accounts'
]

INSTALLED_APPS.extend(HIVEMIND_APPS)

APP_LINKS = [
    { 'title': 'Projects', 'url': reverse_lazy('common:projects') },
    { 'title': 'Issues', 'url': reverse_lazy('defects:list') },
]

CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'app.urls'
WSGI_APPLICATION = 'app.wsgi.application'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            path.join(SRC_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.context_processors.app_version',
                'app.context_processors.app_links',
                'app.context_processors.pending_registrations',
            ],
        },
    },
]

SECRET_KEY = environ.get('SECRET_KEY', 'default-key')

ALLOWED_HOSTS = ['*']

LOGIN_URL = reverse_lazy('login-url')
LOGIN_REDIRECT_URL = reverse_lazy('home-url')

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Australia/Sydney'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_ROOT = path.join(BASE_DIR, "static")

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    path.join(SRC_DIR, "static"),
)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} - {asctime} - {name} - {process:d} - {thread:d} - {message}',
            'style': '{',
        },
        'default': {
            'format': '{levelname} - {asctime} - {name} - {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': path.join(BASE_DIR, 'volume', 'debug.log'),
            'formatter': 'verbose',
        },
        'console':{
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'default',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
