# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 06:37
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dirts', '0007_auto_20151211_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='date_changed',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='defect',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
