# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainevent',
            name='sequence_nr',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='domainevent',
            unique_together=set([('aggregate_type', 'aggregate_id', 'sequence_nr')]),
        ),
    ]
