# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainevent',
            name='aggregate_type',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
