# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 13:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0007_auto_20170627_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('short_summary', models.CharField(blank=True, max_length=140)),
                ('clients', models.ManyToManyField(blank=True, to='common.Manufacturer')),
                ('projects', models.ManyToManyField(blank=True, to='common.Project')),
                ('tags', models.ManyToManyField(blank=True, to='taggit.Tag')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
